### ISSUE TITLE
Only show loading signs during noticeable loading times

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#175]
Split out from #171, mentioned in: https://github.com/ISDuBA/ISDuBA/issues/171#issue-2352800801

When loading advisories, for a brief moment the loading sign flashes up. This is unnecessary for a split second waiting time.

**Comment by cintek** [comment]
One problem here is that we don't know how much time requests take because we don't know anything about the performance of the backend where it is running later and the internet speed could vary. A solution could be to show the indicator always for a minimum of time that is more than a flash up but only that long that it does not disturb the users.

**Comment by s-l-teichmann** [comment]
... or start showing the loading sign after a short grace time.  When we get the answer before the end of the grace time we don't need to show the loading sign. Which in return may lead to the situation that the grace time expires, the loading sign shows up and in this moment the request is back -> Flash again only later.

A more optical appealing way might be a loading sign that increases it's contrast  intensity against the background the longer it takes. So if we return back early the intensity diff would be small and not disturbing. But I don't know if we need such a level of sophistication here.

The only real solution is to make the backend *slower* ...  ;-)
