### ISSUE TITLE
Rework Advisory details

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#177]
Currently, the information shown about advisories are a port of the [csaf webview](https://github.com/csaf-poc/csaf_webview).

However, there are certain stylistic shortcomings and adjustments that should be made to make it more usable.

How to properly rework the view is part of this issue.

https://github.com/ISDuBA/ISDuBA/issues/142 is part of this issue

**Comment by ThomasJunk** [comment]
#142 is closed. For the rest this ticket is very unspecific. I suggest to close this unspecific ticket and open specific ones (focussed on one task at a time) later.

**Comment by luisa-beerboom** [comment]
Some ideas:
1. It might be a good idea to use tabs (see https://flowbite-svelte.com/docs/components/tabs) to organize Vulnerabilities overview, Product tree, Vulnerabilities, Notes, References and Revision history sections. This would reduce scrolling and cause the section selection to be located in one central place, so that the user won't have to constantly scroll up/down in order to close the last/find the next section he wants to look at. We'd have to think about which of the 6 sections should be opened by default, though.
2. Lists in the collapsible sections should have roughly similar styles
3. In Product tree most if not all top-level sub-titles seem to be "Branches"
4. The SSVC/comment area should be properly built into the layout so that it doesn't cover other content on smaller layouts. This means: Remove the absolute css class, if there is to be a split screen, do it through grid or flexbox.

**Comment by luisa-beerboom** [comment]
- The note subsections are currently discerned via category, which, according to the format documentation, should be an enum. If there are multiple notes with the same categories, this causes the subsections to be indiscernable until the user opens them and reads title and text.
   - The title may be optional, but putting it in the subsection title line would help: Something like `general: Affected operating systems`.
   - Since category is an enum, we could think about replacing it with an icon, only showing the text value as a tooltip when hovering over this icon. So something like `◆ Affected operating systems` .
- The reference subsection is a list of entries with values category, summary and url.
  - `category` is an enum which may only have two values: self and external. There has got to be a better way of displaying this information than writing it out as `Category: self`. Maybe use icons, maybe split the area into two lists, one for each category. Maybe don't show the titles all together, make one short column just for the category and put the rest of the data in the other.
  - Why not make url a clickable link? That would do away with the necessity of pointing out via row title, that it is an url.
  - After all that, the point of ´summary` would probably be clear without the title as well.

**Comment by luisa-beerboom** [comment]
The SSVC wizard should probably either be an actual dialogue, fixed to an absolute position _on top_ of the current layout or at least have the same size as the standard size of the comment input area, which it currently seems to be replacing.
This would be to ensure that there's no jumping elements on the view

**Comment by luisa-beerboom** [comment]
Revision history:
- Number should probably be the first column
    -  Title of that column could potentially be abbreviated to `#`
- Summary should probably have text wrapping
- the list itself should have side-scrolling

**Comment by luisa-beerboom** [comment]
Vulnerabilities Overview:
- Legend should be a wrapping flexbox covering the available width, the legend elements should be single line (i.e. no text wrapping)
- The `TOTAL RESULT` and `CVE-...` column titles could be rotated 90° counter clockwise to save space and therefore allow for easier overview
- The Product column...
    - should have text wrapping for its entries
    - Should probably be sticky and therewith fixed to the side of the list, constantly visible, no matter what CVE is being viewed
