### ISSUE TITLE
More information for debugging

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#21]
To make debugging easier we should show some build information in the client. Therefore, we want to show a build number of the client (#19) and the backend (#20) in the client. One possible place to do so would be an "About" section in the configuration menu of the client.

**Comment by ThomasJunk** [comment]
Commit f8fbac2 has a basic version of this.

**Comment by bernhardreiter** [comment]
@koplas for the backend and the version number:

https://tip.golang.org/doc/go1.18#go-version says that go now embeds some info, is worth trying out, the problem is just that `git describe` does not deliver a correct Semver re-release version number. So the solution in the Makefile of csaf_distribution still seems cool for the backend. We could add and display the new go build information additionally.

**Comment by koplas** [comment]
> @koplas for the backend and the version number:
> 
> https://tip.golang.org/doc/go1.18#go-version says that go now embeds some info, is worth trying out, the problem is just that `git describe` does not deliver a correct Semver re-release version number. So the solution in the Makefile of csaf_distribution still seems cool for the backend. We could add and display the new go build information additionally.

Currently go only includes useful version information on `go install` or `go get` and not `go build`. For more info see https://github.com/golang/go/issues/50603.
As a workaround, the version information can be overwritten with:
```sh
go build -ldflags "-X main.version=v0.1.0" ....
```
If the issue is fixed the flag can be removed, without changing the code.
