### ISSUE TITLE
Diff: Unresponsive application

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#332]
1. Go to `Search`
2. Open the diff box

Result: Application becomes unresponsive. (The console shows endless requests to `/api/tempdocuments`).

1. Open an advisory with multiple versions
2. Click on "Show changes"

Result: Application becomes unresponsive. (The console shows endless requests to `/api/documents/<some_id>`).

**Comment by ThomasJunk** [comment]
Commit 804a1d3 should improve the situation.

Explanation: 

The watcher on `$appStore.app.diff.isDiffBoxOpen` issues subsequent loading of $things which in turn modifies the store (a newly fetched token is persisted in the store) which in turn leads to a whole re-evaluation of the store-object which in turn triggers the watcher to be re-evaluated as well; and because the condition is true it triggers the whole cycle again.

The solution implemented creates a derived state which watches only whether the diffbox property has changed:

`$: isDiffBoxOpen = $appStore.app.diff.isDiffBoxOpen;`

and according to those changes 

`$: if (isDiffBoxOpen) {`

additional things are done (which in effect breaks the infinite loop).

**Comment by ThomasJunk** [comment]
@cintek please test.

**Comment by cintek** [comment]
Thanks @ThomasJunk, with e2868e28987896e92595a33359a5b51454c55e32 I added the part for the second case.
