### ISSUE TITLE
Dashboard: Configurable queries

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#361]
Stored queries are a mighty tool to get only those advisories that are important to a user. On the other hand they are not-so-easy to configure. That's why the application will offer pre-defined queries. As long as neither admin nor user creates own queries those queries will be shown on the dashboard.

If the user is not satisfied to 100% with the pre-defined queries they will have the chance to configure own queries and which of them will be shown on the dashboard.

**Comment by bernhardreiter** [comment]
## technical considerations
It should be a simple solution as we aim to have good default queries and changes will only be done seldom.

The original idea is to just have the client decide according to the name and the source of the query. So if there is a query for dashboard-news from the user, use it. Otherwise use the global one.   Same with "recent".

So if the user creates a query with "dashboard-news" in the name the existence of the query already saves the wish to not see the global query on the dashboard.

We may blend out dashboard queries from the query selector on the search page
as well both global and user ones.
