### ISSUE TITLE
Limit displayed name lengths

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#391]
Too long names, for example for users or queries, can disrupt the UI or just feel out of place.

Examples being the usernames in the sidebar (name simply cut off with an induced scrollbar), or long query names on the search page (those similarly expanding the search page for themselves only.)

**Comment by bernhardreiter** [comment]
But names for queries and users are chosen by the system administrator or the users itself, so it should be okay to have them.  Maybe an allowed line break is often enough?

**Comment by cintek** [comment]
Either use a line break or cut-off the text and use an ellipsis. The following screenshot shows:

- At the top: How the queries are display now.
- In the middle: The queries with a line break.
- At the bottom: The queries with an ellipsis (the max width is smaller then in the middle because we cut-off text anyway)


![queries3](https://github.com/user-attachments/assets/376489b2-1c52-4425-9036-09ecf6038bdd)

**Comment by JanHoefelmeyer** [comment]
We should limit the length using ellipses

**Comment by bernhardreiter** [comment]
Line breaks work better if the layout is left aligned.

I think using `...` is suboptimal, as users will have chosen their query descriptions deliberately. So I think linebreaks up to a point and then also using more queries lines should work well enough. In case of several lines of queries, they should be in a section which is has a common border to the right.

**Comment by JanHoefelmeyer** [comment]
Remedied via https://github.com/ISDuBA/ISDuBA/commit/2acce6dec655db403e96afdc21fbe0c545ec91cf
