### ISSUE TITLE
Log download does not work

### ISSUE THREAD

**Issue by s-l-teichmann** [ISDuBA/ISDuBA#637]
Production build on main:
![no-log-download](https://github.com/user-attachments/assets/e9e3b922-1bfe-4498-a34b-fd90ebf2d2c3)

Trying to download the log of a feed results in a network error.

**Comment by s-l-teichmann** [comment]
Turns out that adblockers prevent these downloads.

**Comment by cintek** [comment]
> Turns out that adblockers prevent these downloads.

Since you're not the only one using an adblocker it might be good to prevent confusion by:

- detect adblockers (there are multiple tutorials in the web how to do this) and show a warning next to the button or
- if the request fails with the status code 600 add some text in the error message to explain that adblockers could prevent a successful download. But of course we should not show this text at every error message with code 600 because it also appears if the backend is down.

**Comment by koplas** [comment]
> > Turns out that adblockers prevent these downloads.
> 
> Since you're not the only one using an adblocker it might be good to prevent confusion by:
> 
>     * detect adblockers (there are multiple tutorials in the web how to do this) and show a warning next to the button or
> 
>     * if the request fails with the status code 600 add some text in the error message to explain that adblockers could prevent a successful download. But of course we should not show this text at every error message with code 600 because it also appears if the backend is down.

I would not recommend including heuristics that can detect ad blockers because ad blockers constantly adapt to avoid detection. Other programs like security software can cause the same kind of problems. Correctly detecting the reason for the error inside a web application is impossible.

The reason for the blocked request is the EasyPrivacy List. It blocks `/log?count=`, which is used to download the logs. We can reorder the parameters while requesting the logs to avoid this issue.

**Comment by cintek** [comment]
> The reason for the blocked request is the EasyPrivacy List. It blocks `/log?count=`, which is used to download the logs. We can reorder the parameters while requesting the logs to avoid this issue.

If the the adblockers adapt quickly to detection reordering the parameters also doesn't sound like a sustainable solution. Then in my opinion it would be better to rename the endpoint.

**Comment by s-l-teichmann** [comment]
> Then in my opinion it would be better to rename the endpoint.

`/api/sources/feeds/the_endpoint_that_must_not_be_named`
