### ISSUE TITLE
Alex wants to see existing and work on comments of an advisory and all its documents to save time for colleagues

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#7]
* Backend can already save comments.
 * need to see related comments
 * Alex want to summarize results seen in a diff of a new document to the same advisory

**Comment by cintek** [comment]
With 72cea3f7544a51e5a9ef2ba85112818712b8dca5 Alex can see the comments of a document and write or update own comments. The next step is to show all comments for an advisory.

**Comment by cintek** [comment]
In the meantime the comment section shows some improvements: It prevents empty comments are ones with a length above 10000 characters. An indicator displays the number of entered characters and its font changes to a bold & red when the comment exceeds the limit. If there are no comments the string "No comments available." is visible so users know that the application isn't loading any comments because there are none.
