### ISSUE TITLE
Show the user that opening the profile page opens a new tab

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#83]

**Comment by bernhardreiter** [comment]
A new tab should not be opened by us actively.

**Comment by cintek** [comment]
@bernhardreiter what do you mean by "actively"? At this time the user has to click on the `Profile` tab to open the profile page.

Since the profile page is part of Keycloak IMHO it makes sense to open it in a new tab. And to indicate that a click on the `Profile` tab leads to a new tab our idea was to use an icon (a rectangle with an arrow showing to the top right as in many other applications).

**Comment by bernhardreiter** [comment]
An icon that qualifies the menu entry as one that will lead to a completely different page is an improvement. (As opposed to menu entries that lead to a new page within our main application.)
Login and profile are the same I guess, so both would need that icon.

The question is why we should open a new tab with one of them. Login does not open a new tab IIRC.

**Comment by bernhardreiter** [comment]
Can we give keycloak a backlink, so it will redirect to our application after the editing of the user account is done?

**Comment by cintek** [comment]
> Login and profile are the same I guess, so both would need that icon.

Good argument.

> The question is why we should open a new tab with one of them. Login does not open a new tab IIRC.

Because the login process is a short one but when you navigate through the profile page you could have to go back in the browser many times until you get back to our application. But I guess that is the reason for the next comment:


> Can we give keycloak a backlink, so it will redirect to our application after the editing of the user account is done?

I don't know but in Keycloak you can edit `Personal info`, `Accounty security` and/or `Application` so it wouldn't be good to redirect the user after editing the first one because it could be that the user wants to edit the sedond also.

Another idea: Use an iframe for the profile page. That way the user has still the context of our application (the sidebar) and can navigate to another site very quickly.

**Comment by bernhardreiter** [comment]
Hmm the logout also goes to the keycloak somehow (at least I hope that I get logged out of keycloak). Maybe login, logout and option all need to go under one subpage or sub menu and there we make sure that this is outside.

Add the icon for the time being to profile as a first improvement.

I could imagine that keycloak has the ability to go back to the application somehow.

**Comment by JanHoefelmeyer** [comment]
Reworked the profile page, issue obsolete

**Comment by JanHoefelmeyer** [comment]
Seems like this is no longer obsolete:
https://github.com/ISDuBA/ISDuBA/issues/111#issuecomment-2082173196

**Comment by ThomasJunk** [comment]
The referring issue is closed so I close this one

**Comment by ThomasJunk** [comment]
Commit 0abd867 introduces a new environment variable for the client: `PUBLIC_APPLICATION_URI" which should be documented.

`PUBLIC_APPLICATION_URI` allows us to call keycloak with parameters that allow keycloak to route back to our application. _CAVE_: Using a hash based URI caused problems so I used

`PUBLIC_APPLICATION_URI="http://localhost:5173/"`as the configuration instead of `PUBLIC_APPLICATION_URI="http://localhost:5173/#/login"`. 

So I think this solves the issue.

@JanHoefelmeyer can you confirm?

**Comment by JanHoefelmeyer** [comment]
Yes, only documentation still needs to be added.

**Comment by JanHoefelmeyer** [comment]
Well, by now the application uri no longer needs to be configured, so the documentation has become obsolete. Works and thus can be closed.
