### ISSUE TITLE
Automatically expand deletion-comparison entries

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#89]
If two documents are compared,  Removed entries can be expanded for more information regarding any specific entry.

However, this cannot be undone except for all at once by contracting the entire removed-part.

**Comment by JanHoefelmeyer** [comment]
The added and changed entries are expanded, so the deleted entries should match.

**Comment by cintek** [comment]
> The added and changed entries are expanded, so the deleted entries should match.

The thought behind this implementation was that users probably are more interested in things which were added or replaced than in those which were removed. That's why the server only serves added and replaced entries in the first request and the client has to separately request entries which were removed.

**Comment by JanHoefelmeyer** [comment]
In that case, works as intended
